server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cartlink
    username: apps
    password: apps
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.example.com
    port: 587
    username: your_username
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG
    dev.paul.cartlink: DEBUG

jwt:
  expiration: 86400000  # 24 hours in milliseconds
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c6b1d4f7e0a3

rsa:
  private-key: ${user.home}/.cartlink/certs/private.pem
  public-key: ${user.home}/.cartlink/certs/public.pem

jte:
  developmentMode: true